-- ============================================
-- MariaDB to Oracle Migration Script (DDL)
-- Target Schema: HM_BUSAN
-- ============================================

-- 1. COM_MENU
CREATE TABLE HM_BUSAN.COM_MENU (
    MENU_NO NUMBER(11) NOT NULL,
    MENU_NAME VARCHAR2(100),
    MENU_KIND VARCHAR2(20),
    MENU_AUTH VARCHAR2(20),
    MENU_PAGE_NO NUMBER(11),
    MENU_PAGE_GRP_NO NUMBER(11),
    GUID VARCHAR2(100),
    SITE_NAME VARCHAR2(100),
    VISIBLE_ORDER NUMBER(11),
    IS_WEBUSE NUMBER(1),
    WEB_ICON_CLASS VARCHAR2(30),
    MENU_TYPE VARCHAR2(10),
    LINK_VIEW_TYPE VARCHAR2(10),
    CONSTRAINT PK_COM_MENU PRIMARY KEY (MENU_NO)
);

-- 2. CM_CFG_LAYOUT_VIEW_ENV
CREATE TABLE HM_BUSAN.CM_CFG_LAYOUT_VIEW_ENV (
    VIEW_KIND VARCHAR2(100) NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    MENU_NM VARCHAR2(100),
    REF_CYCLE NUMBER(11) DEFAULT 0,
    THEME VARCHAR2(20) DEFAULT 'gray',
    TITLE_ALIGN VARCHAR2(10) DEFAULT 'left',
    CONSTRAINT PK_CM_CFG_LAYOUT_VIEW_ENV PRIMARY KEY (VIEW_KIND, USER_ID)
);

-- 3. COM_MENU_WIDGET
CREATE TABLE HM_BUSAN.COM_MENU_WIDGET (
    GUID VARCHAR2(100) NOT NULL,
    SYS_CODE VARCHAR2(50),
    MENU_NAME VARCHAR2(100),
    SCOND_USE NUMBER(1),
    GRP_USE NUMBER(1) DEFAULT 0,
    VIEW_SCOPE VARCHAR2(20) DEFAULT 'user',
    CONSTRAINT PK_COM_MENU_WIDGET PRIMARY KEY (GUID)
);

-- 4. COM_MENU_LAYOUT
CREATE TABLE HM_BUSAN.COM_MENU_LAYOUT (
    GUID VARCHAR2(100) NOT NULL,
    MENU_NAME VARCHAR2(100),
    GRP_TYPE VARCHAR2(20),
    SCOND_USE NUMBER(1),
    RT_USE NUMBER(1),
    CONSTRAINT PK_COM_MENU_LAYOUT PRIMARY KEY (GUID)
);

-- 5. COM_USER
CREATE TABLE HM_BUSAN.COM_USER (
    USER_ID VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    DEPT_NAME VARCHAR2(30),
    POS_NAME VARCHAR2(10),
    EMAIL VARCHAR2(100),
    OFFICE_TEL VARCHAR2(20),
    CELL_TEL VARCHAR2(20),
    AUTH VARCHAR2(10),
    USE_FLAG NUMBER(1),
    DEV_GRP_NO NUMBER(10),
    AUTH_GRP_NO NUMBER(10),
    MANAGE NUMBER(1),
    PARENT_ID VARCHAR2(20),
    ACCOUNT VARCHAR2(10),
    NETIS_WEB_THEME VARCHAR2(100),
    NETIS_WEB_MENU_MIN VARCHAR2(5),
    ISSHARE NUMBER(1),
    IS_RECV_EMAIL NUMBER(1),
    IS_RECV_SMS NUMBER(1),
    IS_RECV_PUSH NUMBER(1),
    IS_RECV_POLL NUMBER(1),
    USER_PIC BLOB,
    MESSENGER NUMBER(1),
    SEND_AUTH_ITEM VARCHAR2(20),
    PASS_DATE TIMESTAMP,
    PASS_ERR_CNT NUMBER,
    DASHBOARD_AUTH VARCHAR2(20),
    NEWS_AGENCY VARCHAR2(10),
    MINOR_POLL NUMBER(1),
    MAJOR_POLL NUMBER(1),
    CRITICAL_POLL NUMBER(1),
    SMS_GROUP NUMBER(10),
    USER_PC_IP VARCHAR2(255),
    PASS_CHG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOPO_AUTH_GRP_NO NUMBER(11),
    PW_SALT VARCHAR2(50),
    MENU_AUTH_NO NUMBER(11),
    IS_RESET_PW NUMBER(1) DEFAULT 1,
    NOTI_CNT NUMBER(5) DEFAULT 20,
    SSO_YN VARCHAR2(1),
    CHAT_ID VARCHAR2(50),
    CONSTRAINT PK_COM_USER PRIMARY KEY (USER_ID)
);

-- 6. COM_MENU_LAYOUT_TYPE
CREATE TABLE HM_BUSAN.COM_MENU_LAYOUT_TYPE (
    GUID VARCHAR2(100) NOT NULL,
    COND_TYPE VARCHAR2(20) NOT NULL
);

-- Create index for COM_MENU_LAYOUT_TYPE (original had MUL key on GUID)
CREATE INDEX HM_BUSAN.IDX_COM_MENU_LAYOUT_TYPE_GUID ON HM_BUSAN.COM_MENU_LAYOUT_TYPE(GUID);

-- 7. CM_AUTH_MENU_REL
CREATE TABLE HM_BUSAN.CM_AUTH_MENU_REL (
    AUTH_NO NUMBER(11) NOT NULL,
    REL_KEY_NO NUMBER(11) NOT NULL,
    CONSTRAINT PK_CM_AUTH_MENU_REL PRIMARY KEY (AUTH_NO, REL_KEY_NO)
);

-- ============================================
-- End of DDL Script
-- ============================================
